language: node_js
node_js:
  - "0.10"
  - "0.11"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2677cbf97920e95c6152
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
